#!/usr/bin/env bash
#
# report_tool.sh — small fixed entry point backing the generateReport skill.
# Handles the mechanical parts of run-report generation (unique file naming,
# directory creation, start/end timestamps, duration math) so that logic
# lives in exactly one place instead of being re-derived by every agent or
# command that produces a report. Content formatting itself (the metadata
# block, the per-step table) is left to the caller — that's an LLM task, not
# a mechanical one. The one exception is the HTML report: its markup/CSS is
# generated by the dedicated HtmlReportGenerator (html_report_generator.js),
# invoked here so callers never need a new allowlisted command.
#
# Usage:
#   report_tool.sh new-path <flow_name>         # (legacy) ensures execution/report/ exists, prints a unique .md report path
#   report_tool.sh new-paths <flow_name>        # ensures execution/report/ exists, prints HTML_PATH=
#   report_tool.sh start                        # records run-start time, prints it
#   report_tool.sh end                          # prints start/end/duration and real TOKENS_* usage for the run started above
#   report_tool.sh render-html <output-html-path>   # renders the HTML report from JSON given on stdin

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/execution/report"
STATE_FILE="$SCRIPT_DIR/../.run_state"

fail() { echo "❌ $1" >&2; exit 1; }

now_iso() { date -u +"%Y-%m-%d %H:%M:%S UTC"; }

CMD="${1:-}"
[[ -n "$CMD" ]] || fail "Usage: report_tool.sh <new-path|start|end> [args]"
shift || true

case "$CMD" in
  new-path)
    FLOW_NAME="${1:-}"
    [[ -n "$FLOW_NAME" ]] || fail "Usage: report_tool.sh new-path <flow_name>"
    mkdir -p "$REPORT_DIR"
    TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
    echo "execution/report/${FLOW_NAME}-${TIMESTAMP}.md"
    ;;

  new-paths)
    FLOW_NAME="${1:-}"
    [[ -n "$FLOW_NAME" ]] || fail "Usage: report_tool.sh new-paths <flow_name>"
    mkdir -p "$REPORT_DIR"
    TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
    echo "HTML_PATH=execution/report/${FLOW_NAME}-${TIMESTAMP}.html"
    ;;

  render-html)
    OUT_PATH="${1:-}"
    [[ -n "$OUT_PATH" ]] || fail "Usage: report_tool.sh render-html <output-html-path> (JSON data via stdin)"
    command -v node >/dev/null 2>&1 || fail "node is required to render the HTML report but was not found on PATH"
    node "$SCRIPT_DIR/html_report_generator.js" "$OUT_PATH" || fail "HTML report generation failed"
    ;;

  start)
    START_EPOCH="$(date +%s)"
    START_ISO="$(now_iso)"
    {
      echo "START_EPOCH=$START_EPOCH"
      echo "START_ISO=\"$START_ISO\""
    } > "$STATE_FILE"
    echo "$START_ISO"
    ;;

  end)
    [[ -f "$STATE_FILE" ]] || fail "No active run. Run 'report_tool.sh start' first."
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    END_EPOCH="$(date +%s)"
    END_ISO="$(now_iso)"
    ELAPSED=$((END_EPOCH - START_EPOCH))
    (( ELAPSED < 0 )) && ELAPSED=0
    if (( ELAPSED >= 60 )); then
      DURATION="$((ELAPSED / 60))m $((ELAPSED % 60))s"
    else
      DURATION="${ELAPSED}s"
    fi
    echo "START=$START_ISO"
    echo "END=$END_ISO"
    echo "DURATION=$DURATION"
    if command -v node >/dev/null 2>&1; then
      node "$SCRIPT_DIR/token_usage.js" "$PROJECT_ROOT" "${CLAUDE_CODE_SESSION_ID:-}" "$START_EPOCH" "$END_EPOCH" 2>/dev/null || echo "TOKENS_AVAILABLE=false"
    else
      echo "TOKENS_AVAILABLE=false"
    fi
    rm -f "$STATE_FILE"
    ;;

  *)
    fail "Unknown command: $CMD"
    ;;
esac
